# Generated by Django 6.0.1 on 2026-06-10 18:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerciaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('contact_nom', models.CharField(max_length=200, verbose_name='nom du contact')),
                ('contact_telephone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('quartier', models.CharField(max_length=100, verbose_name='quartier')),
                ('adresse_complete', models.TextField(verbose_name='adresse complète')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date de commande')),
                ('date_livraison', models.DateTimeField(blank=True, null=True, verbose_name='date livraison')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_remise', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_ATTENTE', max_length=20)),
                ('position_livraison', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='commerciaux.commercial')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ligne', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='commerciaux.produit')),
            ],
        ),
        migrations.CreateModel(
            name='Opportunite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('contact_nom', models.CharField(default='', max_length=200)),
                ('contact_telephone', models.CharField(blank=True, max_length=30)),
                ('etape', models.CharField(choices=[('PROSPECT', 'Prospect'), ('QUALIFICATION', 'Qualification'), ('OFFRE', 'Offre envoyée'), ('NEGOCIATION', 'Négociation'), ('GAGNE', 'Gagnée'), ('PERDU', 'Perdue'), ('REPORTE', 'Reportée')], db_index=True, default='PROSPECT', max_length=20)),
                ('probabilite', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('montant_estime', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('montant_final', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture_prevue', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunite', to='commandes.commande')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunites', to='commerciaux.commercial')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['commercial', 'statut', 'date'], name='commandes_c_commerc_fe172e_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', 'date'], name='commandes_c_statut_c2a52f_idx'),
        ),
    ]
