# Generated by Django 6.0.1 on 2026-06-10 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='contenu')),
                ('contact_nom', models.CharField(blank=True, max_length=200, verbose_name='contact lié')),
                ('is_lu', models.BooleanField(default=False, verbose_name='lu')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='date lecture')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='date envoi')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL, verbose_name='expéditeur')),
                ('visite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='visites.visite', verbose_name='visite liée')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VISITE', 'Nouvelle visite assignée'), ('COMMANDE', 'Commande validée'), ('OBJECTIF', 'Objectif atteint'), ('ZONE', 'Sortie de zone'), ('INACTIVITE', 'Alerte inactivité'), ('MESSAGE', 'Nouveau message'), ('SYSTEME', 'Notification système')], max_length=20, verbose_name='type')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('NORMALE', 'Normale'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='NORMALE', max_length=20, verbose_name='priorité')),
                ('titre', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(verbose_name='message')),
                ('objet_type', models.CharField(blank=True, max_length=50, verbose_name="type d'objet")),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('is_lue', models.BooleanField(default=False, verbose_name='lue')),
                ('is_envoyee', models.BooleanField(default=False, verbose_name='envoyée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='date création')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='date lecture')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['destinataire', 'is_lue'], name='notificatio_destina_acf0f7_idx'), models.Index(fields=['type', 'date_creation'], name='notificatio_type_32c0dc_idx')],
            },
        ),
    ]
