# Generated by Django 6.0.1 on 2026-06-10 18:35

import apps.commerciaux.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='référence')),
                ('nom', models.CharField(db_index=True, max_length=200, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('categorie', models.CharField(choices=[('ELECTRONIQUE', 'Électronique'), ('ALIMENTAIRE', 'Alimentaire'), ('TEXTILE', 'Textile'), ('SERVICES', 'Services'), ('AUTRE', 'Autre')], max_length=20, verbose_name='catégorie')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('prix_gros', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='prix gros')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(db_index=True, default=apps.commerciaux.models.generate_matricule, max_length=50, unique=True, verbose_name='matricule')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('CONGE', 'En congé'), ('SUSPENDU', 'Suspendu'), ('INACTIF', 'Inactif')], db_index=True, default='ACTIF', max_length=20, verbose_name='statut')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="date d'embauche")),
                ('derniere_visite', models.DateTimeField(blank=True, null=True, verbose_name='dernière visite')),
                ('total_ventes', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total ventes cumulées')),
                ('vehicule', models.CharField(blank=True, max_length=100, verbose_name='véhicule')),
                ('immatriculation', models.CharField(blank=True, max_length=50, verbose_name='immatriculation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerciaux_crees', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipe_commerciaux', to=settings.AUTH_USER_MODEL, verbose_name='manager responsable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_profile', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commerciaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObjectifCommercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel')], max_length=20, verbose_name='période')),
                ('annee', models.PositiveIntegerField(default=2026, verbose_name='année')),
                ('mois', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='mois')),
                ('trimestre', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='trimestre')),
                ('cible', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='montant cible')),
                ('realise', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='montant réalisé')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date fin')),
                ('is_atteint', models.BooleanField(default=False, verbose_name='objectif atteint')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectifs', to='commerciaux.commercial', verbose_name='commercial')),
            ],
            options={
                'verbose_name': 'Objectif Commercial',
                'verbose_name_plural': 'Objectifs Commerciaux',
                'ordering': ['-annee', '-mois'],
            },
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Format international requis. Ex: +237 6XX XXX XXX', regex='^\\+[0-9]{1,4}[0-9\\s\\-\\(\\)]{6,20}$')], verbose_name='numéro')),
                ('type', models.CharField(choices=[('MOBILE', 'Mobile'), ('FIXE', 'Fixe'), ('TRAVAIL', 'Travail'), ('WHATSAPP', 'WhatsApp')], default='MOBILE', max_length=20, verbose_name='type')),
                ('is_principal', models.BooleanField(default=False, verbose_name='numéro principal')),
                ('is_whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telephones', to='commerciaux.commercial', verbose_name='commercial')),
            ],
            options={
                'verbose_name': 'Téléphone',
                'verbose_name_plural': 'Téléphones',
                'ordering': ['-is_principal', 'type'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=100, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('polygone', models.TextField(blank=True, null=True, verbose_name='zone géographique')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='ville principale')),
                ('pays', models.CharField(default='Cameroun', max_length=100, verbose_name='pays')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='zones_managed', to=settings.AUTH_USER_MODEL, verbose_name='manager responsable')),
            ],
            options={
                'verbose_name': 'Zone',
                'verbose_name_plural': 'Zones',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ZoneAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Zone', max_length=100, verbose_name='nom')),
                ('polygone', models.TextField(verbose_name='zone géographique')),
                ('date_debut', models.DateField(verbose_name='date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='date fin')),
                ('active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones_assignees', to='commerciaux.commercial', verbose_name='commercial')),
                ('manager', models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='zones_assignees', to=settings.AUTH_USER_MODEL, verbose_name='manager')),
            ],
            options={
                'verbose_name': 'Zone assignée',
                'verbose_name_plural': 'Zones assignées',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AddIndex(
            model_name='commercial',
            index=models.Index(fields=['statut', 'manager'], name='commerciaux_statut_1f265f_idx'),
        ),
        migrations.AddIndex(
            model_name='commercial',
            index=models.Index(fields=['user', 'statut'], name='commerciaux_user_id_927c66_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='objectifcommercial',
            unique_together={('commercial', 'periode', 'annee', 'mois', 'trimestre')},
        ),
        migrations.AlterUniqueTogether(
            name='telephone',
            unique_together={('commercial', 'numero')},
        ),
    ]
