# Generated by Django 6.0.1 on 2026-06-10 18:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('commerciaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_nom', models.CharField(default='', max_length=200, verbose_name='nom du contact')),
                ('contact_telephone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('quartier', models.CharField(blank=True, max_length=100, verbose_name='quartier')),
                ('adresse_complete', models.TextField(blank=True, verbose_name='adresse')),
                ('type_visite', models.CharField(choices=[('REGULIERE', 'Visite régulière'), ('RECOUVREMENT', 'Recouvrement'), ('LIVRAISON', 'Livraison'), ('PRESENTATION', 'Présentation produit'), ('AUTRE', 'Autre')], default='REGULIERE', max_length=20, verbose_name='type')),
                ('date_prevue', models.DateTimeField(verbose_name='date prévue')),
                ('date_effective', models.DateTimeField(blank=True, null=True, verbose_name='date effective')),
                ('duree_estimee', models.PositiveIntegerField(default=30, verbose_name='durée estimée (min)')),
                ('objectif', models.TextField(blank=True, verbose_name='objectif de la visite')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('EFFECTUEE', 'Effectuée'), ('REPORTEE', 'Reportée'), ('ANNULEE', 'Annulée')], db_index=True, default='PLANIFIEE', max_length=20, verbose_name='statut')),
                ('checkin_position', models.TextField(blank=True, null=True, verbose_name='position check-in')),
                ('checkin_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='heure check-in')),
                ('checkout_position', models.TextField(blank=True, null=True, verbose_name='position check-out')),
                ('checkout_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='heure check-out')),
                ('duree_reelle', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée réelle (min)')),
                ('compte_rendu', models.TextField(blank=True, verbose_name='compte-rendu')),
                ('actions_suivantes', models.TextField(blank=True, verbose_name='actions suivantes')),
                ('satisfaction_client', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='satisfaction client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visite', to='commandes.commande', verbose_name='commande associée')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='commerciaux.commercial', verbose_name='commercial')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_prevue'],
            },
        ),
        migrations.CreateModel(
            name='RapportVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echantillons_distribues', models.PositiveIntegerField(default=0, verbose_name='échantillons distribués')),
                ('besoins_client', models.TextField(blank=True, verbose_name='besoins identifiés')),
                ('obstacles', models.TextField(blank=True, verbose_name='obstacles rencontrés')),
                ('prochaine_action', models.CharField(blank=True, max_length=200, verbose_name='prochaine action')),
                ('date_prochaine_visite', models.DateTimeField(blank=True, null=True, verbose_name='date prochaine visite')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visites/photos/', verbose_name='photo')),
                ('signature', models.TextField(blank=True, verbose_name='signature électronique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produits_presentes', models.ManyToManyField(blank=True, related_name='rapports', to='commerciaux.produit', verbose_name='produits présentés')),
                ('visite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rapport', to='visites.visite', verbose_name='visite')),
            ],
            options={
                'verbose_name': 'Rapport de Visite',
                'verbose_name_plural': 'Rapports de Visite',
            },
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['commercial', 'statut', 'date_prevue'], name='visites_vis_commerc_6a50a6_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['contact_nom', 'date_prevue'], name='visites_vis_contact_25e8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='visite',
            index=models.Index(fields=['statut', 'date_prevue'], name='visites_vis_statut_029125_idx'),
        ),
    ]
