# Generated by Django 5.1.2 on 2026-06-13 17:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visites', '0002_manager_controle_pdv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visite',
            new_name='visites_vis_manager_f33cb1_idx',
            old_name='visites_vis_manager_idx',
        ),
        migrations.RenameIndex(
            model_name='visite',
            new_name='visites_vis_point_v_771c33_idx',
            old_name='visites_vis_pdv_idx',
        ),
        migrations.AddField(
            model_name='visite',
            name='note_controle',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='note de contrôle'),
        ),
        migrations.AlterField(
            model_name='rapportvisite',
            name='constats',
            field=models.TextField(blank=True, verbose_name='constats'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='manager',
            field=models.ForeignKey(limit_choices_to={'role': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='visites', to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='point_vente_nom',
            field=models.CharField(default='', max_length=200, verbose_name='point de vente'),
        ),
    ]
