# Generated by Django 6.0.1 on 2026-05-20 09:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerciaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_sociale', models.CharField(db_index=True, max_length=200, verbose_name='raison sociale')),
                ('nom_contact', models.CharField(blank=True, max_length=150, verbose_name='nom du contact')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Format international requis.', regex='^\\+[0-9]{1,4}[0-9\\s\\-\\(\\)]{6,20}$')], verbose_name='téléphone')),
                ('adresse', models.CharField(max_length=300, verbose_name='adresse')),
                ('ville', models.CharField(db_index=True, max_length=100, verbose_name='ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('pays', models.CharField(default='Cameroun', max_length=100, verbose_name='pays')),
                ('position', models.TextField(blank=True, null=True, verbose_name='position GPS')),
                ('secteur', models.CharField(blank=True, choices=[('RETAIL', 'Retail / Grande distribution'), ('HORECA', 'Hôtellerie / Restauration'), ('SANTE', 'Santé / Pharmaceutique'), ('EDUCATION', 'Éducation'), ('INDUSTRIE', 'Industrie'), ('SERVICES', 'Services'), ('AUTRE', 'Autre')], max_length=20, verbose_name='secteur')),
                ('potentiel', models.CharField(choices=[('A', 'A - Très fort'), ('B', 'B - Fort'), ('C', 'C - Moyen'), ('D', 'D - Faible')], default='C', max_length=5, verbose_name='potentiel')),
                ('is_actif', models.BooleanField(db_index=True, default=True, verbose_name='client actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('commercial_referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='commerciaux.commercial', verbose_name='commercial référent')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['ville', 'secteur'], name='clients_cli_ville_01f68d_idx'), models.Index(fields=['commercial_referent', 'is_actif'], name='clients_cli_commerc_d2e7cc_idx'), models.Index(fields=['potentiel', 'is_actif'], name='clients_cli_potenti_ba2e5e_idx')],
            },
        ),
    ]
