# Generated by Django 6.0.1 on 2026-06-10 18:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerciaux', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_alerte', models.CharField(choices=[('SORTIE', 'Sortie de zone'), ('ENTREE', 'Entrée dans zone'), ('INACTIVITE', 'Inactivité prolongée')], max_length=20)),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('LUE', 'Lue'), ('TRAITEE', 'Traitée')], default='NOUVELLE', max_length=20)),
                ('position', models.TextField()),
                ('distance_zone_m', models.FloatField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='commerciaux.commercial')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
                ('zone_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='commerciaux.zoneassignee')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueParcours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(verbose_name='position')),
                ('precision', models.FloatField(blank=True, null=True)),
                ('vitesse', models.FloatField(blank=True, null=True)),
                ('cap', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='horodatage')),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_positions', to='commerciaux.commercial')),
            ],
            options={
                'verbose_name': 'Historique parcours',
                'verbose_name_plural': 'Historiques parcours',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['commercial', '-timestamp'], name='gps_histori_commerc_96b3dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='PositionTempsReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(verbose_name='position GPS')),
                ('precision', models.FloatField(blank=True, null=True, verbose_name='précision (m)')),
                ('vitesse', models.FloatField(blank=True, null=True, verbose_name='vitesse (km/h)')),
                ('cap', models.FloatField(blank=True, null=True, verbose_name='cap (degrés)')),
                ('online', models.BooleanField(db_index=True, default=False, verbose_name='en ligne')),
                ('dernier_update', models.DateTimeField(db_index=True, verbose_name='dernière mise à jour')),
                ('commercial', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position_actuelle', to='commerciaux.commercial', verbose_name='commercial')),
            ],
            options={
                'verbose_name': 'Position temps réel',
                'verbose_name_plural': 'Positions temps réel',
                'indexes': [models.Index(fields=['online', 'dernier_update'], name='gps_positio_online_5ea458_idx')],
            },
        ),
    ]
